source 'https://rubygems.org'

gem 'rails', github: "rails/rails"
gem 'sprockets-rails', github: "rails/sprockets-rails"
gem 'sprockets', github: "rails/sprockets"
gem 'sass-rails', github: "rails/sass-rails"
gem 'arel', github: "rails/arel"
gem 'rack', github: "rack/rack"

gem 'pg', '~> 0.18'
gem 'bcrypt', '~> 3.1.7'
gem 'puma'
# gem 'capistrano-rails', group: :development
gem 'active_model_serializers', '~> 0.10.0.rc2'
gem 'rack-cors'
group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
